version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: 24hane
    hostname: 24hane
    environment:
      MYSQL_ROOT_PASSWORD: password42
      MYSQL_DATABASE: checkin_v3
      MYSQL_USER: checkin.local
      MYSQL_PASSWORD: password42
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "3311:3306"
    restart: always