CREATE TABLE USER_INFO
(
    USER_ID       INT                   NOT NULL PRIMARY KEY,
    LOGIN         VARCHAR(50)           NOT NULL,
    IS_ADMIN      BOOLEAN               NOT NULL DEFAULT FALSE,
    CONSTRAINT IDX_UNIQUE UNIQUE (USER_ID)
);

CREATE TABLE CARD_ISSUANCE
(
    IDX             BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID         INT         NOT NULL,
    CARD_ID         VARCHAR(20) NOT NULL,
    START_USE       DATETIME    NOT NULL,
    END_USE         DATETIME    NOT NULL DEFAULT '9999-12-31 23:59:59',
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_INFO (USER_ID),
    CONSTRAINT IDX_UNIQUE UNIQUE (IDX)
);

CREATE TABLE DEVICE_INFO
(
    DEVICE_ID       INT                 NOT NULL PRIMARY KEY,
    CAMPUS          VARCHAR(15)         NOT NULL,
    IO_TYPE         VARCHAR(3)          NOT NULL,
    CONSTRAINT DEVICE_ID_UNIQUE UNIQUE (DEVICE_ID)
);

CREATE TABLE TAG_LOG
(
    IDX             BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TAG_AT          DATETIME    NOT NULL,
    CARD_ID         VARCHAR(15) NOT NULL,
    DEVICE_ID       INT         NOT NULL,
    CONSTRAINT IDX_UNIQUE UNIQUE (IDX)
);

CREATE TABLE PAIR_INFO
(
    IN_DEVICE       INT                 NOT NULL,
    OUT_DEVICE      INT                 NOT NULL,
    CONSTRAINT PAIR_INFO_PK PRIMARY KEY (IN_DEVICE, OUT_DEVICE)
);

# Sample Data

# 사용자 정보 (아이디, 로그인, 관리자 여부 - 0/1)
INSERT INTO USER_INFO (USER_ID, LOGIN, IS_ADMIN) VALUES (12345, 'kristine', 1);

# 카드 발급내역 (아이디, 카드 고유 ID, 카드 발급일, 카드 만료일)
INSERT INTO CARD_ISSUANCE (USER_ID, CARD_ID, START_USE, END_USE) VALUES (12345, '1234567890123', '2019-01-01 00:00:00', '9999-12-31 23:59:59');

# 태깅을 하는 단말 정보 (단말 고유 ID, 캠퍼스 - GAEPO/SEOCHO, 출입 - IN/OUT)
INSERT INTO DEVICE_INFO (DEVICE_ID, CAMPUS, IO_TYPE) VALUES (12, 'GAEPO', 'IN');

# 입-출 짝 정보들 (입장 단말 고유 ID, 퇴장 단말 고유 ID)
INSERT INTO PAIR_INFO (IN_DEVICE, OUT_DEVICE) VALUES (12, 13);

# 태깅한 로그 (태깅한 시간, 카드 고유 ID, 단말 고유 ID)
INSERT INTO TAG_LOG (TAG_AT, CARD_ID, DEVICE_ID) VALUES ('2022-08-19 14:41:44', '8501109000615', 15);
